# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AniLog' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AniLog

  target 'AniLogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AniLogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'SideMenu'

end
